use super::collect_file_summary;
use crate::config::DiscoveredConfig;
use crate::result::{CheckCategory, CheckResult, CheckSummary, Severity};

pub fn print(results: &[CheckResult], summary: &CheckSummary, config: &DiscoveredConfig) {
    let base_dir = config.base_dir.display();

    println!("# shibcheck report");
    println!();
    println!("> {}", base_dir);
    println!();

    // Summary banner
    let status_emoji = if summary.errors > 0 {
        "🔴"
    } else if summary.warnings > 0 {
        "🟡"
    } else {
        "🟢"
    };
    println!(
        "**{}  {} checks | {} passed | {} errors | {} warnings | {} info**",
        status_emoji, summary.total, summary.passed, summary.errors, summary.warnings, summary.info
    );
    println!();

    // Categories
    let categories = [
        CheckCategory::XmlValidity,
        CheckCategory::CrossReferences,
        CheckCategory::Security,
        CheckCategory::Migration,
        CheckCategory::Operational,
    ];

    for category in &categories {
        let cat_results: Vec<_> = results.iter().filter(|r| r.category == *category).collect();
        if cat_results.is_empty() {
            continue;
        }

        let passed = cat_results.iter().filter(|r| r.passed).count();
        let total = cat_results.len();
        let failed: Vec<_> = cat_results.iter().filter(|r| !r.passed).collect();

        println!("## {} ({}/{})", category, passed, total);
        println!();

        if failed.is_empty() {
            println!("All checks passed.");
            println!();
            continue;
        }

        println!("| Status | Code | Location | Message | Suggestion |");
        println!("|--------|------|----------|---------|------------|");

        for result in &cat_results {
            if result.passed {
                continue;
            }

            let badge = match result.severity {
                Severity::Error => "🔴 FAIL",
                Severity::Warning => "🟡 WARN",
                Severity::Info => "🔵 INFO",
            };

            let location = result
                .location
                .as_ref()
                .map(|loc| format!("`{}`", loc))
                .unwrap_or_default();

            let mut suggestion = String::new();
            if let Some(ref s) = result.suggestion {
                suggestion.push_str(&md_escape(s));
            }
            if let Some(ref url) = result.doc_url {
                if !suggestion.is_empty() {
                    suggestion.push(' ');
                }
                suggestion.push_str(&format!("[docs]({})", url));
            }

            println!(
                "| {} | `{}` | {} | {} | {} |",
                badge,
                result.code,
                location,
                md_escape(&result.message),
                suggestion,
            );
        }

        println!();
    }

    // Files section
    let files = collect_file_summary(config);
    if !files.is_empty() {
        println!("## Files");
        println!();
        println!("| Status | Path | Kind |");
        println!("|--------|------|------|");
        for file in &files {
            let icon = if file.found { "✅" } else { "❌" };
            println!("| {} | `{}` | {} |", icon, file.path, file.kind);
        }
        println!();
    }

    println!(
        "---\n*Generated by shibcheck v{}*",
        env!("CARGO_PKG_VERSION")
    );
}

/// Escape pipe characters for markdown table cells.
fn md_escape(s: &str) -> String {
    s.replace('|', "\\|")
}
